package org.kata.yahtzee;

public enum Rules {
    ONES, TWOS, THREES, FOURS, FIVES, SIXES, PAIR, TWO_PAIRS, THREE_OF_KIND, FOUR_OF_KIND, CHANCE, SMALL_STRAIGHT,
    LARGE_STRAIGHT, YAHTZEE, FULL_HOUSE
}
